// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Base64 of the HeartCrackIcon SVG
const faviconBase64 =
  "data:image/svg+xml;base64,PHN2ZyBmaWxsPSIjRkYwMDAwIiB2aWV3Qm94PSIwIDAgMjQgMjQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTExLjk5IDIzLjM4bC0uMDEtLjAxYTguNTIgOC41MiAwIDAwLTIuNzc2LTIuNjA3QzQuODk5IDE3LjgxIDEgMTQuMTIgMSA5Ljk5YzAtMi43MDMgMS4wNy01LjE3OCAyLjg5LTYuOTk0QzYuNzQ0IDExLjg0IDExLjk5IDExLjEyIDExLjk5IDExLjEycy0xLjA2LTYuNjQtMy44OTItOC43MUM1LjkzOCAzLjE3NiA0IDYuMjM5IDQgOS45OWMwIDQuMTMgMy44OSAxNy44MSA4LjIyIDExLjc3QzEyLjk1IDIxLjc3IDExLjk5IDIzLjM4IDExLjk5IDIzLjM4eiIvPjwvc3ZnPg==";

export const metadata: Metadata = {
  title: "Health-Care",
  description: "Generated by create next app",
  icons: {
    icon: faviconBase64,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster richColors position="top-center" />
        {children}
      </body>
    </html>
  );
}
